{{ if .Values.meao.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.meao.name }}
  name: {{ .Values.meao.name }}
spec:
  type: {{ .Values.meao.service.type }}
  ports:
    {{ .Values.meao.service.ports | toYaml | nindent 4 }}
  selector:
    app: {{ .Values.meao.name }}
{{- end }}
