domain: IT_AVEIRO

osm:
  host: nbi.localhost.nip.io

meao:
  name: meao
  enabled: true
  sharedKubectlConfigPath: /configs/
  deployment:
    replicas: 1
    image: ghcr.io/atnog/osm-mec/meao:main
    imagePullPolicy: Always
    restartPolicy: Always
    env:
      KUBECTL_COMMAND: /usr/local/bin/kubectl
      KAFKA_GROUP_ID: "meao"
    ports:
      - containerPort: 8000
        protocol: TCP

  monitoring:
    enabled: true
    name: meao-monitoring
    deployment:
      image: ghcr.io/atnog/osm-mec/meao-monitoring:main
      ports:
        - containerPort: 8001
          protocol: TCP
      imagePullPolicy: Always
      restartPolicy: Always
      env:
        KUBECTL_COMMAND: /usr/local/bin/kubectl
        RAW_METRICS_KAFKA_TOPIC: raw-metrics  # Raw Metrics
        MEH_METRICS_KAFKA_TOPIC: meh-metrics  # MEC Hosts Metrics
        UE_LATENCY_KAFKA_TOPIC: ue-lat
        SEND_CONTAINER_INFO_FREQ: "5"
        KAFKA_GROUP_ID: "meao-monitoring"

  migration:
    enabled: true
    name: meao-migration
    deployment:
      image: ghcr.io/atnog/osm-mec/meao-migration:main
      imagePullPolicy: Always
      restartPolicy: Always
      ports:
        - containerPort: 8002
          protocol: TCP
      env:
        KUBECTL_COMMAND: /usr/local/bin/kubectl
        RAW_METRICS_KAFKA_TOPIC: raw-metrics  # Raw Metrics
        MEH_METRICS_KAFKA_TOPIC: meh-metrics  # MEC Hosts Metrics
        UE_LATENCY_KAFKA_TOPIC: ue-lat
        SEND_CONTAINER_INFO_FREQ: "5"
        KAFKA_GROUP_ID: "meao-migration"

  service:
    type: NodePort
    ports:
      - name: "meao"
        port: 8000
        targetPort: 8000
        nodePort: 30800
      - name: "meao-monitoring"
        port: 8001
        targetPort: 8001
        nodePort: 30801
      - name: "meao-migration"
        port: 8002
        targetPort: 8002
        nodePort: 30802

oss:
  enabled: true
  # host that will be shared by the cfs-portal to the client
  deployment:
    replicas: 1
    image: ghcr.io/atnog/osm-mec/oss:main
    imagePullPolicy: Always
    restartPolicy: Always
    env:
      KAFKA_GROUP_ID: "oss"
  service:
    type: LoadBalancer
    oss_port: 8080
    oss_targetPort: 8080
    ws_port: 8001
    ws_targetPort: 8001

kafka:
  KAFKA_PRODUCER_CONFIG:
    bootstrap_servers: "kafka-controller-headless.osm.svc.cluster.local:9094"
    security_protocol: "SASL_PLAINTEXT"
    sasl_mechanism: "PLAIN"
    sasl_plain_username: "user1"
    sasl_plain_password: "admin"
  KAFKA_CONSUMER_CONFIG:
    bootstrap_servers: "kafka-controller-headless.osm.svc.cluster.local:9094"
    group_id: "group"
    auto_offset_reset: "latest"
    security_protocol: "SASL_PLAINTEXT"
    sasl_mechanism: "PLAIN"
    sasl_plain_username: "user1"
    sasl_plain_password: "admin"

cfsPortal:
  enabled: true
  ossHost: localhost
  deployment:
    replicas: 1
    image: ghcr.io/atnog/osm-mec/cfs-portal:main
    imagePullPolicy: Always
    restartPolicy: Always
    env:
      FEDERATION: True
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
    nodePort: 30000

mongo:
  enabled: true
  deployment:
    replicas: 1
    image: mongo:4.4
  service:
    type: LoadBalancer
    port: 27017
    targetPort: 27017
  username: root
  password: pass

mongoExpress:
  enabled: true
  deployment:
    replicas: 1
    image: mongo-express:latest
  service:
    port: 8081
    targetPort: 8081
  username: root
  password: pass

metricsForwarder:
  name: metrics-forwarder
  enabled: true
  sharedKubectlConfigPath: /configs/
  deployment:
    replicas: 1
    image: ghcr.io/atnog/osm-mec/metrics-forwarder:main
    imagePullPolicy: Always
    restartPolicy: Always
    env:
      KAFKA_GROUP_ID: "forwarder"
    ports:
      - containerPort: 8000
        protocol: TCP
