version: "3"
services:
  oss:
    build: ./oss
    ports:
      - "${OSS_PORT}:${OSS_PORT}"
    volumes:
      - ./oss:/usr/app
    networks:
      - network
    environment:
      - OSM_HOSTNAME=${OSM_HOSTNAME}
      - OSS_HOSTNAME=${OSS_HOSTNAME}
      - OSS_PORT=${OSS_PORT}

  mongo:
    image: mongo
    volumes:
      - app-mongo-db-data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_USER}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_PASSWORD}"
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "${MONGO_EXPRESS_ENABLE_ADMIN}"

  cfs-portal:
    build: ./cfs-portal
    ports:
      - "3000:3000"
    volumes:
      - /usr/app/node_modules
      - ./cfs-portal:/usr/app
    networks:
      - network
    environment:
      CHOKIDAR_USEPOLLING: "true"

networks:
  network:
    driver: bridge

volumes:
  app-mongo-db-data:
