version: "3"
services:
  meao:
    build: ./meao
    ports:
      - "8080:8080"
    networks:
      - network
    environment:
      - OSM_HOSTNAME=${OSM_HOSTNAME}
      - MEAO_HOSTNAME=${MEAO_HOSTNAME}
      - MEAO_PORT=${MEAO_PORT}

  oss:
    build: ./oss
    ports:
      - "3000:3000"
    networks:
      - network

networks:
  network:
    driver: bridge
