apiVersion: v1
kind: Service
metadata:
  labels:
    app: cfs-portal
  name: cfs-portal
spec:
  type: {{ .Values.cfsPortal.service.type }}
  ports:
    - name: "cfs-portal"
      port: {{ .Values.cfsPortal.service.port }}
      targetPort: {{ .Values.cfsPortal.service.targetPort }}
      nodePort: {{ .Values.cfsPortal.service.nodePort }}
  selector:
    app: cfs-portal
