apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cfs-portal
  name: cfs-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cfs-portal
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cfs-portal
    spec:
      containers:
        - env:
          - name: CHOKIDAR_USEPOLLING
            value: "true"
          - name: REACT_APP_OSS_HOST
            value: "{{ .Values.oss.host }}"
          - name: REACT_APP_OSS_PORT
            value: "8080"
          - name: WDS_SOCKET_PORT
            value: "8001"
          image: localhost:5000/cfs-portal:latest
          imagePullPolicy: Always
          name: cfs-portal
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
      volumes:
        - name: cfs-portal-claim0
          persistentVolumeClaim:
            claimName: cfs-portal-claim0
