apiVersion: v1
kind: Service
metadata:
  labels:
    app: cfs-portal
  name: cfs-portal
spec:
  type: NodePort
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    app: cfs-portal
