apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: meao
  name: meao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meao
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: meao
    spec:
      containers:
        - env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: 10.255.32.88:14000
            - name: MONGO_PASSWORD
              value: pass
            - name: MONGO_USER
              value: root
            - name: OSM_HOSTNAME
              value: 10.255.32.88:9999
          image: localhost:5000/meao:latest
          imagePullPolicy: Always
          name: meao
      restartPolicy: Always
