apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: meao
  name: meao
spec:
  replicas: {{ .Values.meao.deployment.replicas }}
  selector:
    matchLabels:
      app: meao
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: meao
    spec:
      containers:
        - env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.kafka.host }}:{{ .Values.kafka.port }}
            - name: MONGO_PASSWORD
              value: {{ .Values.mongo.password }}
            - name: MONGO_USER
              value: {{ .Values.mongo.username }}
            - name: OSM_HOSTNAME
              value: {{ .Values.osm.host }}
          image: {{ .Values.meao.deployment.image }}
          imagePullPolicy: {{ .Values.meao.deployment.imagePullPolicy }}
          name: meao
      restartPolicy: {{ .Values.meao.deployment.restartPolicy }}
