apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-express
  name: mongo-express
spec:
  type: ClusterIP
  ports:
    - name: mongo-express
      port: {{ .Values.mongoExpress.service.port }}
      targetPort: {{ .Values.mongoExpress.service.targetPort }}
  selector:
    app: mongo-express