apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  serviceName: "mongo"
  replicas: {{ .Values.mongo.deployment.replicas }}
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: {{ .Values.mongo.deployment.image }}
          env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.mongo.password }}
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.mongo.username }}
          ports:
            - containerPort: {{ .Values.mongo.service.targetPort }}
              protocol: TCP
          volumeMounts:
            - name: app-mongo-db-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: app-mongo-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi