apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  serviceName: "mongo"
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:4.4
          env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: pass
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: app-mongo-db-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: app-mongo-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi