apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  type: ClusterIP
  ports:
    - name: "mongo"
      port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.service.targetPort }}
  selector:
    app: mongo