apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-express
  name: mongo-express
spec:
  replicas: {{ .Values.mongoExpress.deployment.replicas }}
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: {{ .Values.mongoExpress.deployment.image }}
          env:
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: {{ .Values.mongoExpress.password }}
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: {{ .Values.mongoExpress.username }}
            - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
              value: "true"
            - name: ME_CONFIG_MONGODB_URL
              value: mongodb://{{ .Values.mongoExpress.username }}:{{ .Values.mongoExpress.password }}@mongo:27017/
          ports:
            - containerPort: {{ .Values.mongoExpress.service.targetPort }}
              protocol: TCP