apiVersion: v1
kind: Service
metadata:
  labels:
    app: oss
  name: oss
spec:
  type: {{ .Values.oss.service.type }}
  ports:
    - name: "oss"
      port: {{ .Values.oss.service.oss_port }}
      targetPort: {{ .Values.oss.service.oss_targetPort }}
    - name: "ws"
      port: {{ .Values.oss.service.ws_port }}
      targetPort: {{ .Values.oss.service.ws_targetPort }}
  selector:
    app: oss
