apiVersion: v1
kind: Service
metadata:
  labels:
    app: oss
  name: oss
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 8080
    - name: "8001"
      port: 8001
      targetPort: 8001
      nodePort: 8001
  selector:
    app: oss
