apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oss
  name: oss
spec:
  replicas: {{ .Values.oss.deployment.replicas }}
  selector:
    matchLabels:
      app: oss
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oss
    spec:
      containers:
        - env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.kafka.host }}:{{ .Values.kafka.port }}
            - name: MONGO_PASSWORD
              value: {{ .Values.mongo.password }}
            - name: MONGO_USER
              value: {{ .Values.mongo.username }}
            - name: OSM_HOSTNAME
              value: {{ .Values.osm.host }}
            - name: OSS_PORT
              value: "{{ .Values.oss.service.oss_port }}"
            - name: OSS_WS_PORT
              value: "{{ .Values.oss.service.ws_port }}"
          image: {{ .Values.oss.deployment.image }}
          imagePullPolicy: {{ .Values.oss.deployment.imagePullPolicy }}
          name: oss
          ports:
            - containerPort: {{ .Values.oss.service.oss_targetPort }}
              protocol: TCP
            - containerPort: {{ .Values.oss.service.ws_targetPort }}
              protocol: TCP
      restartPolicy: {{ .Values.oss.deployment.restartPolicy }}