# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Prepare Artifacts
        run: |
          # include/exlude subdirectories/files not capable of being configured in jekyll _config.yaml
          mkdir -p /tmp/site
          cp -t /tmp/site -r README.md osm-mec-logo.png docs _site/index.html _site/assets

          # Generate yang documentation
          cd yang
          pip install pyang==2.6.0 pyangbind==0.8.5
          pyang -f jstree -o /tmp/site/mec-app-descriptor-parameters.html mec-app-descriptor.yang
          cd ..

          # Replace the logo in mec-app-descriptor-parameters.html
          sed -i 's|<a href="[^"]*">|<a href="https://atnog.github.io/osm-mec/docs/index.html">|' /tmp/site/mec-app-descriptor-parameters.html
          # Replace the img tag with the new logo image
          sed -i 's|<img src="[^"]*"[^>]*>|<img src="https://atnog.github.io/osm-mec/osm-mec-logo.png" alt="OSM MEC" style="width:150px;height:43.125px;" />|' /tmp/site/mec-app-descriptor-parameters.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: /tmp/site

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
